#include<stdio.h>
#include<stdlib.h>
#include<string.h>

int convert(char *a,int n);
int main(){
	int length=0;
	int i=0,j=0;
	char *data=NULL,*p=NULL,*len=NULL,*len1=NULL;
	char cct[16]={0},change[10]={0},num1[16]={0},num2[16]={0},num3[16]={0},num4[16]={0},num5[16]={0},num6[16]={0},num7[16]={0},num8[16]={0},num9[16]={0};
	char num10[16]={0},num11[16]={0},num12[16]={0},num13[16]={0},num14[16]={0},num15[16]={0},num16[16]={0},num17[16]={0},num18[16]={0},num19[16]={0},num20[16]={0};
	FILE *fp;

	printf("Content-Type:text/html;charset=gb2312\n\n");
	if(getenv("CONTENT_LENGTH")){
		length=atoi(getenv("CONTENT_LENGTH"));
		data=(char*)malloc(length*sizeof(char));
		memset(data, 0x00, sizeof(data));
		for(i=0;i<length;i++)
			data[i]=getchar();
	}
	//printf(data);
	len=(char*)malloc(length*sizeof(char));
	if((fp=fopen("/param/data/rtsp_queue.bin","wb"))==NULL){
		printf("can not open file \n");
		exit(0);
	}
	for(i=1;i<=16;i++){
		j=0;
		memset(cct,0x00,sizeof(cct));
		memset(change,0x00,sizeof(change));
		cct[0]='c';cct[1]='c';cct[2]='t';
		sprintf(change,"%d",i);
		strcat(cct,change);
		//printf(cct);
		p=strstr(data,cct);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),1,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+6,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),1,fp);
		}
	}
/*±àºÅ1*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num1,0x00,sizeof(num1));
		memset(change,0x00,sizeof(change));
		num1[0]='s';num1[1]='1';
		sprintf(change,"%d",i);
		strcat(num1,change);
		p=strstr(data,num1);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+4,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}
/*±àºÅ2*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num2,0x00,sizeof(num2));
		memset(change,0x00,sizeof(change));
		num2[0]='s';num2[1]='2';
		sprintf(change,"%d",i);
		strcat(num2,change);
		p=strstr(data,num2);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+4,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}

/*±àºÅ3*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num3,0x00,sizeof(num3));
		memset(change,0x00,sizeof(change));
		num3[0]='s';num3[1]='3';
		sprintf(change,"%d",i);
		strcat(num3,change);
		p=strstr(data,num3);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+4,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}

/*±àºÅ4*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num4,0x00,sizeof(num4));
		memset(change,0x00,sizeof(change));
		num4[0]='s';num4[1]='4';
		sprintf(change,"%d",i);
		strcat(num4,change);
		p=strstr(data,num4);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+4,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}

/*±àºÅ5*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num5,0x00,sizeof(num5));
		memset(change,0x00,sizeof(change));
		num5[0]='s';num5[1]='5';
		sprintf(change,"%d",i);
		strcat(num5,change);
		p=strstr(data,num5);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+4,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}

/*±àºÅ6*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num6,0x00,sizeof(num6));
		memset(change,0x00,sizeof(change));
		num6[0]='s';num6[1]='6';
		sprintf(change,"%d",i);
		strcat(num6,change);
		p=strstr(data,num6);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+4,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}

/*±àºÅ7*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num7,0x00,sizeof(num7));
		memset(change,0x00,sizeof(change));
		num7[0]='s';num7[1]='7';
		sprintf(change,"%d",i);
		strcat(num7,change);
		p=strstr(data,num7);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+4,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}

/*±àºÅ8*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num8,0x00,sizeof(num8));
		memset(change,0x00,sizeof(change));
		num8[0]='s';num8[1]='8';
		sprintf(change,"%d",i);
		strcat(num8,change);
		p=strstr(data,num8);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+4,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}

/*±àºÅ9*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num9,0x00,sizeof(num9));
		memset(change,0x00,sizeof(change));
		num9[0]='s';num9[1]='9';
		sprintf(change,"%d",i);
		strcat(num9,change);
		p=strstr(data,num9);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+4,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}

/*±àºÅ10*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num10,0x00,sizeof(num10));
		memset(change,0x00,sizeof(change));
		num10[0]='t';num10[1]='1';num10[2]='0';
		sprintf(change,"%d",i);
		strcat(num10,change);
		p=strstr(data,num10);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+6,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}

/*±àºÅ11*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num11,0x00,sizeof(num11));
		memset(change,0x00,sizeof(change));
		num11[0]='t';num11[1]='1';num11[2]='1';
		sprintf(change,"%d",i);
		strcat(num11,change);
		p=strstr(data,num11);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+6,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}

/*±àºÅ12*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num12,0x00,sizeof(num12));
		memset(change,0x00,sizeof(change));
		num12[0]='t';num12[1]='1';num12[2]='2';
		sprintf(change,"%d",i);
		strcat(num12,change);
		p=strstr(data,num12);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+6,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}

/*±àºÅ13*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num13,0x00,sizeof(num13));
		memset(change,0x00,sizeof(change));
		num13[0]='t';num13[1]='1';num13[2]='3';
		sprintf(change,"%d",i);
		strcat(num13,change);
		p=strstr(data,num13);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+6,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}

/*±àºÅ14*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num14,0x00,sizeof(num14));
		memset(change,0x00,sizeof(change));
		num14[0]='t';num14[1]='1';num14[2]='4';
		sprintf(change,"%d",i);
		strcat(num14,change);
		p=strstr(data,num14);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+6,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}

/*±àºÅ15*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num15,0x00,sizeof(num15));
		memset(change,0x00,sizeof(change));
		num15[0]='t';num15[1]='1';num15[2]='5';
		sprintf(change,"%d",i);
		strcat(num15,change);
		p=strstr(data,num15);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+6,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}

/*±àºÅ16*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num16,0x00,sizeof(num16));
		memset(change,0x00,sizeof(change));
		num16[0]='t';num16[1]='1';num16[2]='6';
		sprintf(change,"%d",i);
		strcat(num16,change);
		p=strstr(data,num16);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+6,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}

/*±àºÅ17*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num17,0x00,sizeof(num17));
		memset(change,0x00,sizeof(change));
		num17[0]='t';num17[1]='1';num17[2]='7';
		sprintf(change,"%d",i);
		strcat(num17,change);
		p=strstr(data,num17);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+6,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}

/*±àºÅ18*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num18,0x00,sizeof(num18));
		memset(change,0x00,sizeof(change));
		num18[0]='t';num18[1]='1';num18[2]='8';
		sprintf(change,"%d",i);
		strcat(num18,change);
		p=strstr(data,num18);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+6,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}

/*±àºÅ19*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num19,0x00,sizeof(num19));
		memset(change,0x00,sizeof(change));
		num19[0]='t';num19[1]='1';num19[2]='9';
		sprintf(change,"%d",i);
		strcat(num19,change);
		p=strstr(data,num19);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			memset(len,0x00,sizeof(len));
			sscanf(p+6,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}

/*±àºÅ20*/
	for(i=1;i<=64;i++){
		j=0;
		memset(num20,0x00,sizeof(num20));
		memset(change,0x00,sizeof(change));
		num20[0]='t';num20[1]='2';num20[2]='0';
		sprintf(change,"%d",i);
		strcat(num20,change);
		p=strstr(data,num20);
		if(i>=1&&i<10){
			memset(len,0x00,sizeof(len));
			sscanf(p+5,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else if(i>=10&&i<64){
			memset(len,0x00,sizeof(len));
			sscanf(p+6,"%[^&]",len);
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
		else{
			j=convert(len,strlen(len));
			fwrite(&j,sizeof(char),4,fp);
		}
	}
	//sprintf(change,"%d",h);
	//printf(change);
	//printf("\t");
	free(len);
	fclose(fp);
	free(data);
}

int convert(char *a,int n){
	int ref,tmp,sum;
	for(tmp=0,sum=0;tmp<n;tmp++){
		sum*=10;
		ref=a[tmp]-'0';
		sum+=ref;
	}
	return sum;
}
